import fs from 'node:fs/promises';
import readline from 'node:readline/promises';
import { connect, delay } from '../browser/index.ts';
import type * as spec from '../browser/spec-types.ts';

const logs: string[] = [];
const client = await connect({ logs });
console.log(`connection open attach session ${client.session.id}`);
console.log(`driver status ${JSON.stringify(await client.driverStatus())}`);

const pages = await client.getPages();
client.setPageId(pages[0].id);
console.log(`devtools url: ${client.getDevToolsFrontEndURL()}`);
const readlineInterface = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    removeHistoryDuplicates: true,
}); await readlineInterface.question('input anything to continue');

if (pages[0].url != 'https://wiki.skland.com/endfield/catalog?typeMainId=1&typeSubId=2') {
    console.log(await client.navigate('https://wiki.skland.com/endfield/catalog?typeMainId=1&typeSubId=2', 'interactive'));
}

// the random sequence in the classnames are definitely generated by some logic
// and it very likely to change after website is updated, so better put them together to make them easier to find
const selectors = {
    cardContainer: 'div.CommonCard__CardContainer-fQKpRL',
    card: 'div.ArmsCard__Border-bHFog',
    documentWrapper: 'div.Document__Wrapper-eLvDYV',
    rarityClasses: [['jnHwkG', 6], ['dVhNsJ', 5], ['eFBkOY', 4], ['gFiiRG', 3]] as [string, number][],
};
const remoteFunctions = {
    // weapon name from card element
    getWeaponName: ((e: HTMLDivElement) => (e.childNodes[0].childNodes[3] as HTMLDivElement).innerText).toString(),
    // scroll into any element
    scrollIntoView: ((e: HTMLElement) => e.scrollIntoView()).toString(),
    // weapon attributes in weapon detail page
    // this site use api data structure and html layout structure that no human and AI can understand
    // ATTENTION this is remote function cannot add type annotation
    // ATTENTION this is remote function cannot reference variables here
    getWeaponAttributes: (() => {
        for (const documentWrapperElement of Array.from(document.querySelectorAll('div.Document__Wrapper-eLvDYV'))) {
            if ((documentWrapperElement?.childNodes[0]?.childNodes[0]?.childNodes[0] as HTMLSpanElement)?.innerText == '属性能力') {
                return [2, 5, 8].map(i => {
                    const lastContainer = documentWrapperElement.childNodes[i]?.childNodes[0];
                    if (i == 8) {
                        // @ts-ignore but you are still allowed to write a harmless comment in remote function
                        return lastContainer && lastContainer.children.length > 1
                        // @ts-ignore
                            ? `${lastContainer.children[0].innerText}${lastContainer.children[1].innerText}` : null;
                    } else {
                        return (documentWrapperElement.childNodes[i]?.childNodes[0]?.childNodes[0] as HTMLSpanElement)?.innerText;
                    }
                });
            }
        }
    }).toString(),
};

interface WeaponData {
    name: string,
    rarity: number,
    attributes: string[],
}
const weapondata: WeaponData[] = JSON.parse(await fs.readFile('data/weapon.json', 'utf-8'));

await client.waitElements(selectors.cardContainer, 10);
// NOTE these elements are invalidated after navigation
// // actually js in browser also gets invalidated after navigation, this is kind of reasonable
// so add a stale flag to reload element if need or avoid reload if not stale
let elementsAreValid = true;
let cardElements = await client.querySelectorAll(selectors.card, { maxDepth: 3 });
// console.log(JSON.stringify(cardElements, undefined, 2));
const cardElementCount = cardElements.length;
console.log(`card count ${cardElementCount}`);

// name and rarity is available in returned node infomation
for (const cardElement of cardElements) {
    const children = cardElement?.value?.children?.[0]?.value?.children;
    if (!children || (children.length != 4 && children.length != 5)) {
        console.log(`card element unexpected layout`, JSON.stringify(cardElement, undefined, 2));
        continue;
    }

    const weaponName = children[children.length - 1]?.value?.children?.[0]?.value?.nodeValue?.trim();
    if (!weaponName) {
        console.log(`card element not found name in children[3].innerText`, JSON.stringify(cardElement, undefined, 2));
        continue;
    }
    let entry = weapondata.find(w => w.name == weaponName);
    if (!entry) {
        console.log(`create new entry for previously unknown weapon ${weaponName}`);
        entry = { name: weaponName, rarity: undefined, attributes: undefined };
        weapondata.push(entry);
    }

    // rarity can be found by decoration style
    if (!entry.rarity) {
        const classname = children[children.length - 2]?.value?.attributes?.['class'];
        if (classname && typeof classname == 'string') {
            const classnames = classname.split(' ');
            const rarity = selectors.rarityClasses.find(([c]) => classnames.includes(c))?.[1];
            if (!rarity) {
                console.log(`card element not found rarity by known mapping, ` +
                    `classname is ${classname}`, JSON.stringify(cardElement, undefined, 2));
            } else {
                entry.rarity = rarity;
            }
        } else {
            console.log(`card element not found rarity style in children[2]`, JSON.stringify(cardElement, undefined, 2));
            // not continue
        }
    }
}

for (let cardIndex = 0; cardIndex < cardElementCount; cardIndex += 1) {
    if (!elementsAreValid) {
        await client.waitElements(selectors.cardContainer, 10);
        cardElements = await client.querySelectorAll(selectors.card, { maxDepth: 3 });
        elementsAreValid = true;
    }

    const cardElement = cardElements[cardIndex];
    const children1 = cardElement?.value?.children?.[0]?.value?.children;
    const weaponName = children1 ? children1[children1.length - 1]?.value?.children?.[0]?.value?.nodeValue?.trim() : null;
    if (!weaponName) {
        console.log(`weapon index ${cardIndex} not found weapon name?`, JSON.stringify(cardElement, undefined, 2));
        continue;
    }
    const entry = weapondata.find(w => w.name == weaponName);
    if (!entry) {
        console.log(`you find a new weapon inside the loop, how?`, JSON.stringify(cardElement, undefined, 2));
        continue;
    }

    // already known, skip
    if (entry.attributes && entry.attributes.length) { continue; }

    // click into weapon detail page
    console.log(`click into ${weaponName}`);
    await client.call(remoteFunctions.scrollIntoView, [cardElement]);
    await client.click(cardElement);
    elementsAreValid = false;

    // search for attributes
    // TODO new layout change at 20260425, lazy to fix this, manual fix for now
    const attributes: string[] = [];
    await client.waitElements(selectors.documentWrapper, 10);
    const evalResult2 = await client.call(remoteFunctions.getWeaponAttributes, []);
    // by the way, 3 star weapon only have 2 attributes, making this condition false, and the last element is {type:"undefined"}
    if (evalResult2.type == 'success' && evalResult2.result.type == 'array'
        && evalResult2.result.value.length == 3 && !evalResult2.result.value.some(v => v.type != 'string'))
    {
        attributes.push(...evalResult2.result.value.map(v => (v as spec.script.StringValue).value.trim()));
    } else {
        console.log(`unexpected eval result2`, JSON.stringify(evalResult2));
    }
    entry.attributes = attributes;
    console.log(`load attributes for ${weaponName}: ${attributes}`);

    // go back
    await delay(3); // wait for my human eye
    await client.go(-1);
}

await fs.writeFile('data/weapon.json', JSON.stringify(weapondata, undefined, 2));
await client.close();
